on:
    release:
        types:
            - published

jobs:
    build:
        permissions:
            contents: write
        runs-on: windows-2022
        steps:
            - name: メインブランチをチェックアウト
              uses: actions/checkout@v3

            - uses: microsoft/setup-msbuild@1ff57057b5cfdc39105cd07a01d78e9b0ea0c14c #v1.3.1

            - name: バージョン番号の取得
              id: version
              run: |
                "version=$('${{ github.event.release.tag_name }}' -replace 'v', '')" >> $env:GITHUB_OUTPUT

            - name: 依存関係の解決
              run: MSBuild -target:Restore

            - name: ビルド
              run: MSBuild -property:Configuration=Release -property:OutputPath=./bin -property:Version=${{ steps.version.outputs.version }}

            - name: アーカイブ化
              run: Compress-Archive ./bin/* -DestinationPath 'ncv-voicevox-${{ steps.version.outputs.version }}.zip'

            - name: リリースページへ添付
              uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 #v0.1.15
              with:
                files: ./*.zip
